# Kubecost running as an Agent is designed for external hosting. The current setup deploys a
# kubecost-agent pod and prometheus server
global:
  thanos:
    enabled: false 
  grafana:
    enabled: false 
    proxy: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    # fsGroup: 65534
    # runAsGroup: 65534
    # runAsUser: 65534

# Sets the image version for the Kubecost agent..
imageVersion: lunar-sandwich.v0.1.2

# Sets the destination where the Kubecost agent connects.
cloudReportingServer: collector.app.kubecost.com:31357

# Cloud Agent enables specific features designed to enhance the metrics exporter deployment
# with enhancements designed for Kubecost Cloud 
cloudAgent: true 
cloudAgentKey: ""
cloudAgentClusterId: my-cluster

# Cloud Agent securely sends data using one-way TLS
cloudAgentTLSCertName: "agent-tls-public-key"
cloudAgentTLSFileName: "files/prod-cloud-cert.pem"

# No Grafana configuration is required.
grafana:
  sidecar:
    dashboards:
      enabled: false
    datasources:
      defaultDatasourceEnabled: false

# Exporter Pod
kubecostMetrics: 
  exporter:
    enabled: true 
    exportClusterInfo: false
    exportClusterCache: false

# Disable cost-analyzer PSP
podSecurityPolicy: 
  enabled: false

# Disable KSM and NodeExporter (?)
prometheus:
  podSecurityPolicy: 
    enabled: false
  nodeExporter:
    enabled: false
  kube-state-metrics:
    enabled: false
    disabled: true
  extraScrapeConfigs: |
    - job_name: kubecost-cloud-agent
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 60s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
      - names:
        - {{ .Release.Name }}-cloud-agent
        type: 'A'
        port: 9005
    - job_name: kubecost-networking
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      # Scrape only the the targets matching the following metadata
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex:  {{ template "cost-analyzer.networkCostsName" . }}
